debug:move

diff --git a/.github/workflows/build_kernel_redmi8_4.19-Universal.yml b/.github/workflows/build_kernel_redmi8_4.19-Universal.yml
--- a/.github/workflows/build_kernel_redmi8_4.19-Universal.yml
+++ b/.github/workflows/build_kernel_redmi8_4.19-Universal.yml
@@ -677,15 +677,16 @@ jobs:
             fi
             make -j$(nproc --all) CC="ccache clang" O=out ARCH=arm64 ${{ env.CUSTOM_CMDS }} ${{ env.EXTRA_CMDS }} ${{ env.GCC_64 }} ${{ env.GCC_32 }} 2>&1|tee error.log
           fi
+          
+          echo "==========EOF=========="
+          cat fs/namei.c || echo "namei.c not found!"
 
           if grep -q "Error 2" "error.log"; then
-            false
-            echo "==========EOF=========="
-            cat fs/namei.c
+            false            
           fi
 
           ## Generate DTBO
-          if [ "${{ env.HAVE_NO_DTBO }}" == "true" ] && [ "${{ env.HAVE_NO_DTBO_TOOL }}" == "true" ] && [ "${{ env.CONSTRUCT }}" != "error" ]; then
+          if [ "${{ env.HAVE_NO_DTBO }}" == "true" ] && [ "${{ env.HAVE_NO_DTBO_TOOL }}" == "true" ]; then
             cd $GITHUB_WORKSPACE/device_kernel
             mkdir dtbo_tool
             cd dtbo_tool
